/**
 * AI Commerce V4.2 - Google Sheets direct-image synchronizer.
 * Bind this script to each Operations Spreadsheet and run installProductImageSyncTriggers() once.
 */
const PRODUCT_SHEET='Products';
const SOURCE_IMAGE_HEADERS=['Product Image','Image 2','Image 3','Image 4','Image 5'];
const RESOLVED_HEADERS=['Resolved Image 1','Resolved Image 2','Resolved Image 3','Resolved Image 4','Resolved Image 5'];
const FILE_ID_HEADERS=['_Image File ID 1','_Image File ID 2','_Image File ID 3','_Image File ID 4','_Image File ID 5'];
const HASH_HEADERS=['_Image Hash 1','_Image Hash 2','_Image Hash 3','_Image Hash 4','_Image Hash 5'];
function installProductImageSyncTriggers(){const ss=SpreadsheetApp.getActive();ScriptApp.getProjectTriggers().forEach(t=>{if(['onProductSheetEdit','syncProductSheetImages'].includes(t.getHandlerFunction()))ScriptApp.deleteTrigger(t)});ScriptApp.newTrigger('onProductSheetEdit').forSpreadsheet(ss).onEdit().create();ScriptApp.newTrigger('syncProductSheetImages').timeBased().everyMinutes(5).create();syncProductSheetImages();}
function onProductSheetEdit(e){if(!e||!e.range||e.range.getSheet().getName()!==PRODUCT_SHEET)return;syncProductSheetImages();}
function syncProductSheetImages(){const sh=SpreadsheetApp.getActive().getSheetByName(PRODUCT_SHEET);if(!sh||sh.getLastRow()<2)return;const map=ensureHeaders_(sh),over=new Map();sh.getImages().forEach(img=>{try{const a=img.getAnchorCell();over.set(`${a.getRow()}:${a.getColumn()}`,img)}catch(_){}});for(let row=2;row<=sh.getLastRow();row++)for(let i=0;i<5;i++)syncImageSlot_(sh,row,map[SOURCE_IMAGE_HEADERS[i]],map[RESOLVED_HEADERS[i]],map[FILE_ID_HEADERS[i]],map[HASH_HEADERS[i]],over,i+1);}
function ensureHeaders_(sh){const last=Math.max(1,sh.getLastColumn()),h=sh.getRange(1,1,1,last).getDisplayValues()[0].map(v=>String(v).trim()),req=[...SOURCE_IMAGE_HEADERS,...RESOLVED_HEADERS,...FILE_ID_HEADERS,...HASH_HEADERS];req.forEach(x=>{if(!h.includes(x)){h.push(x);sh.getRange(1,h.length).setValue(x)}});const m={};h.forEach((x,i)=>m[x]=i+1);return m;}
function syncImageSlot_(sh,row,srcCol,resCol,idCol,hashCol,over,slot){const src=sh.getRange(row,srcCol),resolved=sh.getRange(row,resCol),idCell=sh.getRange(row,idCol),hashCell=sh.getRange(row,hashCol),oldId=String(idCell.getDisplayValue()||'').trim();let url=extractUrl_(src),blob=null;const grid=over.get(`${row}:${srcCol}`);if(grid){try{blob=grid.getBlob()}catch(_){}}if(!blob&&!url){const v=src.getValue();if(v&&typeof v==='object'&&typeof v.getContentUrl==='function'){try{blob=UrlFetchApp.fetch(v.getContentUrl()).getBlob()}catch(_){}}}if(url){trashFile_(oldId);resolved.setValue(url);idCell.clearContent();hashCell.clearContent();return}if(blob){const hash=blobHash_(blob),oldHash=String(hashCell.getDisplayValue()||'').trim();if(oldId&&oldHash===hash){resolved.setValue(driveViewUrl_(oldId));return}trashFile_(oldId);const ext=(blob.getContentType()||'image/jpeg').split('/')[1]||'jpg',product=String(sh.getRange(row,1).getDisplayValue()||`row-${row}`).replace(/[^\w\-.]+/g,'_').slice(0,80);blob.setName(`${product}-image-${slot}.${ext}`);const file=DriveApp.createFile(blob);try{file.setSharing(DriveApp.Access.ANYONE_WITH_LINK,DriveApp.Permission.VIEW)}catch(_){}idCell.setValue(file.getId());hashCell.setValue(hash);resolved.setValue(driveViewUrl_(file.getId()));return}trashFile_(oldId);resolved.clearContent();idCell.clearContent();hashCell.clearContent();}
function extractUrl_(cell){const f=String(cell.getFormula()||'').trim(),m=f.match(/^=IMAGE\(\s*["']([^"']+)["']/i);if(m)return m[1];const v=cell.getDisplayValue();return /^https?:\/\//i.test(String(v||'').trim())?String(v).trim():'';}
function blobHash_(blob){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,blob.getBytes()).map(b=>(b+256)%256).map(b=>b.toString(16).padStart(2,'0')).join('');}
function driveViewUrl_(id){return `https://drive.google.com/uc?export=view&id=${encodeURIComponent(id)}`;}
function trashFile_(id){if(!id)return;try{DriveApp.getFileById(id).setTrashed(true)}catch(_){}}
